# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sdurgan <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/20 19:13:53 by sdurgan           #+#    #+#              #
#    Updated: 2018/11/21 12:26:22 by sdurgan          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: ft_display_file

ft_display_file:
	gcc main.c -Wall -Werror -Wextra -o ft_display_file

clean:
	rm -f *.o

fclean:
	rm -f ft_display_file
