FROM alpine:3.4
RUN apk update
RUN apk add vim

# to run: e.g. docker build -t ex00 .
# to see: docker image ls
# -t stands for tag-name of image
# . is a directory where docker-build is to search a Dockerfile

# to run an image docker run --rm -ti ex00 /bin/sh
